### ISSUE TITLE
Readme tweaks

### ISSUE THREAD

**Issue by geekingfrog** [Holmusk/three-layer#69]
* One typo: just after `proto-lens`: Protobu~g~f
* The link for `co-log` points to `relude`
* Also, I find the description for `co-log` ill-suited. I would assume the intended audience is has more an engineering mindset, but "composable contravariant comonadic logging library" seems straight out of an academic paper. If someone is comfortable with all of that, they are probably too busy writing another cool library using their latest paper, for other people, it's just off-putting.
How about `composable and configurable logging library`?

**Comment by chshersh** [comment]
@geekingfrog Thanks for telling about typos. I fixed them in `master`. 

Regarding the description of `co-log`: I think that the current description illustrates the main ideas behind the library well. I've added to README a link to the blog post about `co-log` where all design and architecture decisions are described in detail. `Contravariant` typeclass is one of the primary and fundamental typeclasses in Haskell (like `Functor` or `Monad`). `Comonad` is also important, just not that common. Mentioning the fact that the library uses `Contravariant` and `Comonad` typeclasses underhood tells more about the library and gives more hints about how you will use it rather than just saying `configurable`. _Configurable_ is a vague word. How exactly configurable: via functions in code, via TOML file, via clicking buttons on some logging client? The intended audience is Haskell engineers. Ideas like `Functor` and `Monad` initially appeared in academia. But nowadays every Haskell engineer is familiar with those concepts in Haskell. `Contravariant` and `Comonad` might not be as popular as `Functor` and `Monad`, but `co-log` library (and corresponding blog post) tries to explain these concepts and use them to solve real-life production problems so that these typeclasses can be adapted easily.
