### ISSUE TITLE
Add type synonym for `Jwt` Effect

### ISSUE THREAD

**Issue by rashadg1030** [Holmusk/three-layer#74]
Should these be turned into a type synonym?
https://github.com/Holmusk/three-layer/blob/c99a1d5d3b410c280d069d66bb6da84e694fc9bd/src/Lib/Effects/Jwt.hs#L27
https://github.com/Holmusk/three-layer/blob/c99a1d5d3b410c280d069d66bb6da84e694fc9bd/src/Lib/Effects/Jwt.hs#L40
Like:
`type WithJwt r m = (MonadIO m, MonadReader r m, Has JwtSecret r)`
Also, I've noticed in some modules the type variable `r` in these constraint synonyms is replaced with `env`. Which one is better or does it depend?

**Comment by chshersh** [comment]
@rashadg1030 We have `MonadJwt` effect so you don't need to use these three constraints:

https://github.com/Holmusk/three-layer/blob/c99a1d5d3b410c280d069d66bb6da84e694fc9bd/src/Lib/Effects/Jwt.hs#L18-L20

So, ideally, in your library code outside of the effects implementation, you shouldn't use `Has JwtSecret` and `MonadReader`

**Comment by rashadg1030** [comment]
I see. I'm asking because here I notice you use this pattern:
https://github.com/Holmusk/three-layer/blob/c99a1d5d3b410c280d069d66bb6da84e694fc9bd/src/Lib/Effects/Session.hs#L34
There is also `WithDb` and other effects with these custom constraints. When should you use these and when not?

**Comment by chshersh** [comment]
@rashadg1030 `WithSessio` is a local type alias for convenience in this module, shouldn't be used outside of this module. `WithDb`, `WithError` and `WithLog` are special cases because they are specializations of common effects. And they are used in libraries.

1. `WithDb`: because it's quite cumbersome to put every SQL query (or even query functions) into a separate effect, works for now).
2. `WithError` is just `MonadError AppErrror` for brevity
3. `WithLog` is a specialization of `Colog.WithLog` (again, for brevity).

**Comment by rashadg1030** [comment]
@chshersh Got it. Thank you!
